# Generated by Django 4.1 on 2022-09-20 11:45

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_newlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlisting',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='description',
            field=models.TextField(max_length=1000000000.0),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='startingBid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
        migrations.AlterField(
            model_name='newlisting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
