# Generated by Django 4.1 on 2022-09-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_newlisting_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewListing',
            new_name='Listing',
        ),
    ]
