# Generated by Django 4.1.1 on 2022-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_startingbid_currency_listing_startingprice_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='feedback',
        ),
        migrations.AddField(
            model_name='listing',
            name='feedback',
            field=models.ManyToManyField(blank=True, to='auctions.comment'),
        ),
    ]
