# Generated by Django 4.1.1 on 2022-09-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_bid_listing_remove_bid_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentPrice',
        ),
    ]
