# Generated by Django 4.1.1 on 2022-09-30 12:39

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_listing_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentPrice',
            field=models.ManyToManyField(default=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Starting Price'), related_name='latestBid', to='auctions.bid'),
        ),
    ]
