# Generated by Django 4.1.1 on 2022-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentPrice',
            field=models.ManyToManyField(related_name='latestBid', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Closed')], default='Active'),
        ),
    ]
