# Generated by Django 4.1 on 2022-10-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(choices=[('True', 'Active'), ('False', 'Closed')], default='Active'),
        ),
    ]
