# Generated by Django 4.1 on 2022-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (2, 'Closed')], default='Active'),
        ),
    ]
