# Generated by Django 4.1.1 on 2022-10-05 09:17

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_alter_listing_startingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingPrice',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Starting Price'),
        ),
    ]
