# Generated by Django 4.1.1 on 2022-10-05 09:21

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_listing_startingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
