# Generated by Django 4.1.1 on 2022-10-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_alter_bid_bid_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categoryname',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categorylisting', to='auctions.category'),
        ),
    ]
