# Generated by Django 4.1.1 on 2022-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_alter_watchlist_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Title', max_length=100, unique=True, verbose_name=''),
        ),
    ]
