# Generated by Django 4.1.1 on 2022-10-07 09:32

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categoryname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorylisting', to='auctions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingPrice',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)], verbose_name='Price'),
        ),
    ]
